### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by Raghwendra-Dey** [cp-tools/cf-tool#11]
Since, the previous releases contained a major bug of mis-spelling in the `settings.Host`, where a `/` was given instead of `.` in `codeforces.com`, I was trying to use it but couldn't because of the same. It would be great for us, who are not willing to tinker around with the dependencies and all, and just want to install the binary, if you could release a fresh release with the latest bug-free code.
It would also be good if you release a `codeforces blog` informing the community about your project.

**Comment by infalmo** [comment]
Oh, wow. I've released it, but with the same tag. So auto updating is not possible sadly. Could you try downloading it and running it?

**Comment by infalmo** [comment]
Yea, I'm working on a general backend to extract various information from codeforces and will surely do write the blog once the project is stable!

**Comment by Raghwendra-Dey** [comment]
okay! I'll try running it myself locally!!

**Comment by infalmo** [comment]
I just checked the latest release, and yes, the bug has been patched in it!
