### ISSUE TITLE
Generated template doesn't have a name

### ISSUE THREAD

**Issue by confusedman1** [cp-tools/cf-tool#12]
## Bug description
When I generate the template using `cf gen`, it produces a `.cpp` instead of `<folder_name>.cpp`. Also, because it doesn't have a name, the file is hidden from normal view and isn't recongnized as a C++ file.

## Steps to reproduce
1. Parse a problem/contest
2. Go to a problem subfolder and do `cf gen`

## System Details
 - macOS Catalina

**Comment by infalmo** [comment]
Fixed in the latest release 30f33d9 (v1.1.1).
