### ISSUE TITLE
Option to not generate a contest folder every time problem is parsed

### ISSUE THREAD

**Issue by confusedman1** [cp-tools/cf-tool#14]
## Problem related to feature request
Whenever I parse a contest, for example contest `1234`, the tool generates `contest/1234/`. Now if I want to parse another contest I would have to cd back to the parent directory otherwise I would have something like `contest/contest/<contest_id>`.

## Feature proposal to be implemented
It would be nice if the tool just generated `1234/` when I parse contest `1234` instead of `contest/1234/`.

*Thanks!, and good luck on your new tool.*

**Comment by infalmo** [comment]
Yes, I plan on adding something like a default workspace, so that unless explicitly prevented, all parsing is done to that folder (wherever you call `cf fetch` from). Maybe once the new tool is out!

Thanks for the suggestion!

**Comment by infalmo** [comment]
View README for updates.
