### ISSUE TITLE
Typo in setings.go

### ISSUE THREAD

**Issue by gnojus** [cp-tools/cf-tool#7]
`Settings.Host = "https://codeforces/com"`
should be a dot.

**Comment by infixint943** [comment]
Do you wish to be added as a maintainer?
I'd be glad if you join to help me out!

**Comment by gnojus** [comment]
Sure, I could implement the register/unregister features that still aren't
merged in cf-tool.

**Comment by infalmo** [comment]
Yea, would be great!
I've sent an invite to join the organisation if you want to...
